### ISSUE TITLE
Rounding of corners does not scale

### ISSUE THREAD

**Issue by finngl** [kevinsqi/react-piano#43]
The rounding of the downward corners always have the same diameter, which make the keys look quite silly in a very small scale.

**Comment by kevinsqi** [comment]
Yeah, I didn't want to bake in responsive styling behavior directly into the component, so I chose a border-radius that looks good by default at medium-to-large key sizes but not tiny ones. 

I'm still not sure if I should change the default CSS here (it would be a breaking change for existing users) but it is an option. However, you can customize the styling yourself easily and are encouraged to do so! You could add this CSS:

```css
.ReactPiano__Key--accidental {
    border-radius: 0 0 2px 2px;
}
.ReactPiano__Key--natural {
    border-radius: 0 0 2px 2px;
}
```

If you want to have responsive styles depending on how wide each key is, you could implement it with something like this:

```jsx
import { Piano, MidiNumbers } from 'react-piano';
import _ from 'lodash';

render() {
  const pianoWidth = 500;
  const noteRange = { first: MidiNumbers.fromNote('c3'), last: MidiNumbers.fromNote('f5') };
  const numNaturalNotes = _.range(noteRange.first, noteRange.last).filter((note) => !MidiNumbers.getAttributes(note).isAccidental);
  const naturalKeyWidth = pianoWidth / numNaturalNote;

  return (
    <Piano className={naturalKeyWidth < 8 ? 'ReactPiano--small-keys' : null} noteRange={noteRange} width={pianoWidth} />
  );
}
```

And in a stylesheet:

```css
.ReactPiano--small-keys .ReactPiano__Key--accidental {
    border-radius: 0 0 2px 2px;
}
.ReactPiano--small-keys .ReactPiano__Key--natural {
    border-radius: 0 0 2px 2px;
}
```

Does that help get you what you need?
